version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/songs_db

  mongo:
    image: mongo:4.4
    container_name: songs_db
    ports:
      - "27017:27017"
