version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/songs_db
      - FLASK_DEBUG=0
    depends_on:
      - mongodb
    volumes:
      - ./songs.json:/app/songs.json

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
